services:
  postgres:
    image: postgres:16.0
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - leitner-volume:/var/lib/postgresql/data
  minio:
    image: 'minio/minio:latest'
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: 'root'
      MINIO_ROOT_PASSWORD: 'password'
    volumes:
      - minio_storage:/data
    command: server --console-address ":9001" /data

volumes:
  leitner-volume: { }
  minio_storage: { }
